export const ROUTES = {
    Login:'/login',
    Recruitment:{
        Master:{
            Rounds:'/rec/master/rounds',
            InterviewRounds:'/rec/master/interview-rounds',
            QuestionBank:'/rec/master/question-bank',
            State:'/rec/master/state',
            Department:'/rec/master/department',
            Country:'/rec/master/country',
            City:'/rec/master/city',
            Bussiness:'/rec/master/bussiness'
        },
        CreateJob:'/rec/create-job',
        ViewJobs:'/rec/view-job',
        trackJobProgree:'/rec/track-job'
    },
    Home:'/',
    About:'/about'
}