// export const BASE_URL = 'https://trg-portal.herokuapp.com/api/v1/'
export const BASE_URL = 'http://localhost:8000/api/v1/'

export const Round = 'round'
export const Business = 'business'
export const City = 'city'
export const Country = 'country'
export const Department = 'department'
export const InterviewRounds = 'interviewRound'
export const QuestionBank = 'questionBank'
export const State = 'state'
export const UserSignUp = 'signup'
export const UserLogin = 'login'
export const Job = 'job'