// export const BASE_URL = 'https://trg-portal.herokuapp.com/api/v1/'
export const BASE_URL = 'https://trg-portal.vercel.app/api/v1/'
// export const BASE_URL = 'http://localhost:8000/api/v1/' 



// RECRUITMENT
export const Round = 'round'
export const Business = 'business'
export const City = 'city'
export const Country = 'country'
export const Department = 'department'
export const InterviewRounds = 'interviewRound'
export const QuestionBank = 'questionBank'
export const State = 'state'
export const UserSignUp = 'signup'
export const UserLogin = 'login'
export const Job = 'job'
export const Profile = 'profile'
export const workShift = 'workshift'
export const workStyle = 'workstyle'
export const workType = 'worktype'
export const workmode = 'work'
export const jobDescription = 'jobDescription'
export const band = 'band'
export const compensation = 'compensation'
export const currency = 'currency'
